import type { Product } from '../types';

export const products: Product[] = [
  {
    id: 'linen-coat-01',
    category: 'clothing',
    name: 'Oversized Linen Coat',
    artist: null,
    price: 340,
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Ecru', 'Slate', 'Noir'],
    images: ['https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=600&q=80'],
    stock: 8,
    badge: 'New',
    description: 'A relaxed-fit linen coat with dropped shoulders and an oversized silhouette. Made from enzyme-washed Belgian linen for a naturally soft hand feel.',
  },
  {
    id: 'silk-shirt-02',
    category: 'clothing',
    name: 'Raw Silk Shirt',
    artist: null,
    price: 185,
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Ivory', 'Sage'],
    images: ['https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=600&q=80'],
    stock: 14,
    badge: null,
    description: 'A fluid raw silk shirt with a relaxed collar and mother-of-pearl buttons. The slightly textured weave catches light beautifully.',
  },
  {
    id: 'print-abstract-01',
    category: 'art',
    name: 'Composition No. 7',
    artist: 'Mira Solano',
    price: 220,
    sizes: ['A3', 'A2', '50×70cm'],
    colors: null,
    images: ['https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=600&q=80'],
    stock: 25,
    badge: 'Limited',
    description: 'Archival giclée print on Hahnemühle Photo Rag. Signed and numbered edition of 50.',
  },
  {
    id: 'print-landscape-02',
    category: 'art',
    name: 'Pacific Dusk',
    artist: 'James Osei',
    price: 180,
    sizes: ['A3', 'A2'],
    colors: null,
    images: ['https://images.unsplash.com/photo-1549490349-8643362247b5?w=600&q=80'],
    stock: 12,
    badge: null,
    description: 'Captured at golden hour on the California coastline. Printed on museum-grade cotton rag with pigment inks.',
  },
  {
    id: 'bag-leather-01',
    category: 'accessories',
    name: 'Structured Tote',
    artist: null,
    price: 495,
    sizes: null,
    colors: ['Tan', 'Black', 'Forest'],
    images: ['https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=600&q=80'],
    stock: 5,
    badge: 'Almost Gone',
    description: 'Full-grain vegetable-tanned leather with a structured silhouette. Ages beautifully with use. Interior suede lining with magnetic closure.',
  },
  {
    id: 'candle-01',
    category: 'objects',
    name: 'Hand-Poured Soy Candle',
    artist: 'Studio Wax',
    price: 48,
    sizes: ['200ml', '400ml'],
    colors: ['Amber', 'Vetiver', 'Hinoki'],
    images: ['https://images.unsplash.com/photo-1572726729207-a78d6feb18d7?w=600&q=80'],
    stock: 40,
    badge: null,
    description: 'Hand-poured soy wax candle with cotton wicks and essential oil blends. Approximately 45-hour burn time for the 400ml size.',
  },
];
