import type { Airport, Flight } from '../types';

export const airports: Airport[] = [
  { code: 'LHR', name: 'London Heathrow', city: 'London', country: 'UK' },
  { code: 'JFK', name: 'John F. Kennedy', city: 'New York', country: 'US' },
  { code: 'DXB', name: 'Dubai International', city: 'Dubai', country: 'UAE' },
  { code: 'NRT', name: 'Narita International', city: 'Tokyo', country: 'JP' },
  { code: 'CDG', name: 'Charles de Gaulle', city: 'Paris', country: 'FR' },
  { code: 'SIN', name: 'Changi Airport', city: 'Singapore', country: 'SG' },
  { code: 'SYD', name: 'Kingsford Smith', city: 'Sydney', country: 'AU' },
  { code: 'LAX', name: 'Los Angeles International', city: 'Los Angeles', country: 'US' },
];

export const flights: Flight[] = [
  {
    id: 'ba-001',
    airline: 'British Airways',
    flightNumber: 'BA 117',
    from: { code: 'LHR', time: '08:15' },
    to: { code: 'JFK', time: '11:30' },
    duration: '7h 15m',
    stops: 0,
    price: { economy: 549, business: 1840, first: 3200 },
    seatsLeft: 4,
  },
  {
    id: 'vs-002',
    airline: 'Virgin Atlantic',
    flightNumber: 'VS 3',
    from: { code: 'LHR', time: '11:00' },
    to: { code: 'JFK', time: '14:15' },
    duration: '7h 15m',
    stops: 0,
    price: { economy: 489, business: 1620, first: null },
    seatsLeft: 12,
  },
  {
    id: 'aa-003',
    airline: 'American Airlines',
    flightNumber: 'AA 100',
    from: { code: 'LHR', time: '13:45' },
    to: { code: 'JFK', time: '17:00' },
    duration: '7h 15m',
    stops: 0,
    price: { economy: 512, business: 1750, first: 2990 },
    seatsLeft: 8,
  },
  {
    id: 'ek-004',
    airline: 'Emirates',
    flightNumber: 'EK 201',
    from: { code: 'DXB', time: '02:30' },
    to: { code: 'JFK', time: '08:10' },
    duration: '14h 40m',
    stops: 0,
    price: { economy: 680, business: 2450, first: 4800 },
    seatsLeft: 22,
  },
  {
    id: 'sq-005',
    airline: 'Singapore Airlines',
    flightNumber: 'SQ 25',
    from: { code: 'SIN', time: '23:45' },
    to: { code: 'JFK', time: '06:00' },
    duration: '18h 15m',
    stops: 0,
    price: { economy: 720, business: 2800, first: 5200 },
    seatsLeft: 6,
  },
];
