import type { TemplateDefinition } from './types';

export const templates: TemplateDefinition[] = [
  // ╔══════════════════════════════════════════════╗
  // ║  HOTEL TEMPLATES (10)                        ║
  // ╚══════════════════════════════════════════════╝

  {
    id: 'hotel-grand-luxury',
    name: 'Grand Luxury',
    vertical: 'hotel',
    designFamily: 'opulent',
    description: 'Opulent dark theme with parallax hero and tilt cards',
    previewGradient: 'linear-gradient(135deg, #0f0e0d 0%, #2a1f14 50%, #d4a96a 100%)',
    heroLayout: 'parallax',
    navStyle: 'glass',
    aboutLayout: 'zigzag',
    galleryLayout: 'masonry',
    testimonialsLayout: 'single-slider',
    contactLayout: 'split',
    footerLayout: 'standard',
    animationPreset: 'fade-up',
    threeDEffects: { hero: 'parallax-layers', cards: 'tilt-cards', gallery: 'none', intensity: 60 },
    brandOverrides: { accentColor: '#d4a96a', backgroundColor: '#0f0e0d', textColor: '#ffffff', headingFont: 'Bodoni Moda', bodyFont: 'Jost' },
    heroOverrides: { overlayOpacity: 55, alignment: 'center' },
    sectionStyles: { borderRadius: 'lg', cardStyle: 'glass', sectionSpacing: 'spacious' },
  },
  {
    id: 'hotel-boutique-minimal',
    name: 'Boutique Minimal',
    vertical: 'hotel',
    designFamily: 'ethereal',
    description: 'Clean white aesthetic with elegant serif typography',
    previewGradient: 'linear-gradient(135deg, #faf8f5 0%, #e8e0d4 50%, #8b7355 100%)',
    heroLayout: 'minimal',
    navStyle: 'transparent',
    aboutLayout: 'standard',
    galleryLayout: 'grid-uniform',
    testimonialsLayout: 'minimal-inline',
    contactLayout: 'centered-form',
    footerLayout: 'minimal',
    animationPreset: 'fade-in',
    threeDEffects: { hero: 'none', cards: 'float', gallery: 'none', intensity: 30 },
    brandOverrides: { accentColor: '#8b7355', backgroundColor: '#faf8f5', textColor: '#2d2016', headingFont: 'Cormorant Garamond', bodyFont: 'Jost' },
    heroOverrides: { overlayOpacity: 0, alignment: 'center' },
    sectionStyles: { borderRadius: 'none', cardStyle: 'flat', sectionSpacing: 'spacious' },
  },
  {
    id: 'hotel-tropical-resort',
    name: 'Tropical Resort',
    vertical: 'hotel',
    designFamily: 'tropical',
    description: 'Vibrant island vibes with lush greens and warm accents',
    previewGradient: 'linear-gradient(135deg, #0a2618 0%, #1a4a32 50%, #e8b86d 100%)',
    heroLayout: 'fullscreen-card',
    navStyle: 'glass',
    aboutLayout: 'cards-only',
    galleryLayout: 'carousel',
    testimonialsLayout: 'cards',
    contactLayout: 'card',
    footerLayout: 'standard',
    animationPreset: 'scale-up',
    threeDEffects: { hero: 'float', cards: 'tilt-cards', gallery: 'perspective-grid', intensity: 50 },
    brandOverrides: { accentColor: '#e8b86d', backgroundColor: '#0a2618', textColor: '#f0ebe3', headingFont: 'DM Serif Display', bodyFont: 'DM Sans' },
    heroOverrides: { overlayOpacity: 40, alignment: 'center' },
    sectionStyles: { borderRadius: 'lg', cardStyle: 'glass', sectionSpacing: 'normal' },
  },
  {
    id: 'hotel-urban-chic',
    name: 'Urban Chic',
    vertical: 'hotel',
    designFamily: 'brutalist',
    description: 'Modern city hotel with bold geometry and contrast',
    previewGradient: 'linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #e94560 100%)',
    heroLayout: 'split',
    navStyle: 'solid',
    aboutLayout: 'timeline',
    galleryLayout: 'masonry',
    testimonialsLayout: 'cards',
    contactLayout: 'split',
    footerLayout: 'mega',
    animationPreset: 'slide-in',
    threeDEffects: { hero: 'none', cards: 'tilt-cards', gallery: 'depth-scroll', intensity: 45 },
    brandOverrides: { accentColor: '#e94560', backgroundColor: '#1a1a2e', textColor: '#edf2f4', headingFont: 'Space Mono', bodyFont: 'Space Mono' },
    heroOverrides: { overlayOpacity: 30, alignment: 'left' },
    sectionStyles: { borderRadius: 'sm', cardStyle: 'outlined', sectionSpacing: 'normal' },
  },
  {
    id: 'hotel-mountain-lodge',
    name: 'Mountain Lodge',
    vertical: 'hotel',
    designFamily: 'heritage',
    description: 'Rustic warmth with earth tones and natural textures',
    previewGradient: 'linear-gradient(135deg, #2d1b0e 0%, #5c3d2e 50%, #c17f59 100%)',
    heroLayout: 'classic',
    navStyle: 'transparent',
    aboutLayout: 'full-width-image',
    galleryLayout: 'masonry',
    testimonialsLayout: 'quote-wall',
    contactLayout: 'split',
    footerLayout: 'standard',
    animationPreset: 'fade-up',
    threeDEffects: { hero: 'parallax-layers', cards: 'none', gallery: 'none', intensity: 40 },
    brandOverrides: { accentColor: '#c17f59', backgroundColor: '#1c1210', textColor: '#e8ddd3', headingFont: 'Playfair Display', bodyFont: 'Crimson Text' },
    heroOverrides: { overlayOpacity: 50, alignment: 'left' },
    sectionStyles: { borderRadius: 'md', cardStyle: 'elevated', sectionSpacing: 'spacious' },
  },
  {
    id: 'hotel-art-deco',
    name: 'Art Deco',
    vertical: 'hotel',
    designFamily: 'deco',
    description: 'Glamorous 1920s-inspired with gold accents and geometric patterns',
    previewGradient: 'linear-gradient(135deg, #0d0d0d 0%, #1a1a1a 50%, #c9a84c 100%)',
    heroLayout: 'bold-type',
    navStyle: 'centered',
    aboutLayout: 'zigzag',
    galleryLayout: 'grid-uniform',
    testimonialsLayout: 'single-slider',
    contactLayout: 'card',
    footerLayout: 'centered',
    animationPreset: 'stagger-cascade',
    threeDEffects: { hero: 'none', cards: 'flip-reveal', gallery: 'none', intensity: 55 },
    brandOverrides: { accentColor: '#c9a84c', backgroundColor: '#0d0d0d', textColor: '#f5f0e8', headingFont: 'Poiret One', bodyFont: 'Raleway' },
    heroOverrides: { overlayOpacity: 70, alignment: 'center' },
    sectionStyles: { borderRadius: 'none', cardStyle: 'outlined', sectionSpacing: 'spacious' },
  },
  {
    id: 'hotel-zen-retreat',
    name: 'Zen Retreat',
    vertical: 'hotel',
    designFamily: 'wabi-sabi',
    description: 'Japanese-inspired minimalism with calming neutrals',
    previewGradient: 'linear-gradient(135deg, #f5f0eb 0%, #d4cfc7 50%, #7a8b7a 100%)',
    heroLayout: 'stacked',
    navStyle: 'minimal',
    aboutLayout: 'standard',
    galleryLayout: 'lightbox-focus',
    testimonialsLayout: 'minimal-inline',
    contactLayout: 'centered-form',
    footerLayout: 'minimal',
    animationPreset: 'fade-in',
    threeDEffects: { hero: 'none', cards: 'float', gallery: 'none', intensity: 25 },
    brandOverrides: { accentColor: '#7a8b7a', backgroundColor: '#f5f0eb', textColor: '#2c2c2c', headingFont: 'Noto Serif JP', bodyFont: 'Noto Sans' },
    heroOverrides: { overlayOpacity: 20, alignment: 'center' },
    sectionStyles: { borderRadius: 'sm', cardStyle: 'flat', sectionSpacing: 'spacious' },
  },
  {
    id: 'hotel-coastal-haven',
    name: 'Coastal Haven',
    vertical: 'hotel',
    designFamily: 'coastal',
    description: 'Beachfront serenity with ocean blues and sandy neutrals',
    previewGradient: 'linear-gradient(135deg, #0c2d48 0%, #145374 50%, #5cc8d2 100%)',
    heroLayout: 'classic',
    navStyle: 'glass',
    aboutLayout: 'cards-only',
    galleryLayout: 'carousel',
    testimonialsLayout: 'cards',
    contactLayout: 'map-focus',
    footerLayout: 'standard',
    animationPreset: 'fade-up',
    threeDEffects: { hero: 'parallax-layers', cards: 'tilt-cards', gallery: 'perspective-grid', intensity: 50 },
    brandOverrides: { accentColor: '#5cc8d2', backgroundColor: '#0c2d48', textColor: '#e8f4f8', headingFont: 'Lora', bodyFont: 'Open Sans' },
    heroOverrides: { overlayOpacity: 45, alignment: 'left' },
    sectionStyles: { borderRadius: 'lg', cardStyle: 'glass', sectionSpacing: 'normal' },
  },
  {
    id: 'hotel-heritage-palace',
    name: 'Heritage Palace',
    vertical: 'hotel',
    designFamily: 'noir',
    description: 'Regal elegance with deep jewel tones and ornate details',
    previewGradient: 'linear-gradient(135deg, #1a0a2e 0%, #2d1b4e 50%, #b8860b 100%)',
    heroLayout: 'diagonal',
    navStyle: 'solid',
    aboutLayout: 'timeline',
    galleryLayout: 'masonry',
    testimonialsLayout: 'quote-wall',
    contactLayout: 'split',
    footerLayout: 'mega',
    animationPreset: 'stagger-cascade',
    threeDEffects: { hero: 'depth-scroll', cards: 'tilt-cards', gallery: 'depth-scroll', intensity: 65 },
    brandOverrides: { accentColor: '#b8860b', backgroundColor: '#1a0a2e', textColor: '#f0e6d3', headingFont: 'Outfit', bodyFont: 'Sora' },
    heroOverrides: { overlayOpacity: 60, alignment: 'center' },
    sectionStyles: { borderRadius: 'md', cardStyle: 'elevated', sectionSpacing: 'spacious' },
  },
  {
    id: 'hotel-nordic-frost',
    name: 'Nordic Frost',
    vertical: 'hotel',
    designFamily: 'electric',
    description: 'Scandinavian simplicity with icy blues and clean lines',
    previewGradient: 'linear-gradient(135deg, #e8edf2 0%, #c8d6e5 50%, #576574 100%)',
    heroLayout: 'split',
    navStyle: 'transparent',
    aboutLayout: 'standard',
    galleryLayout: 'grid-uniform',
    testimonialsLayout: 'cards',
    contactLayout: 'centered-form',
    footerLayout: 'centered',
    animationPreset: 'fade-up',
    threeDEffects: { hero: 'none', cards: 'float', gallery: 'none', intensity: 30 },
    brandOverrides: { accentColor: '#576574', backgroundColor: '#f0f3f6', textColor: '#222f3e', headingFont: 'Clash Display', bodyFont: 'Sora' },
    heroOverrides: { overlayOpacity: 25, alignment: 'left' },
    sectionStyles: { borderRadius: 'md', cardStyle: 'flat', sectionSpacing: 'normal' },
  },

  // ╔══════════════════════════════════════════════╗
  // ║  RESTAURANT TEMPLATES (10)                   ║
  // ╚══════════════════════════════════════════════╝

  {
    id: 'restaurant-trattoria',
    name: 'Trattoria',
    vertical: 'restaurant',
    designFamily: 'opulent',
    description: 'Warm Italian charm with terracotta and rustic elegance',
    previewGradient: 'linear-gradient(135deg, #0d0a08 0%, #2a1810 50%, #e85d3a 100%)',
    heroLayout: 'classic',
    navStyle: 'glass',
    aboutLayout: 'zigzag',
    galleryLayout: 'masonry',
    testimonialsLayout: 'cards',
    contactLayout: 'split',
    footerLayout: 'standard',
    animationPreset: 'fade-up',
    threeDEffects: { hero: 'parallax-layers', cards: 'tilt-cards', gallery: 'none', intensity: 50 },
    brandOverrides: { accentColor: '#e85d3a', backgroundColor: '#0d0a08', textColor: '#ffffff', headingFont: 'Bodoni Moda', bodyFont: 'Jost' },
    heroOverrides: { overlayOpacity: 55, alignment: 'left' },
    sectionStyles: { borderRadius: 'lg', cardStyle: 'elevated', sectionSpacing: 'normal' },
  },
  {
    id: 'restaurant-sushi-zen',
    name: 'Sushi Zen',
    vertical: 'restaurant',
    designFamily: 'wabi-sabi',
    description: 'Minimalist Japanese aesthetics with dark moody tones',
    previewGradient: 'linear-gradient(135deg, #0a0a0a 0%, #1a1a2e 50%, #c41e3a 100%)',
    heroLayout: 'minimal',
    navStyle: 'minimal',
    aboutLayout: 'standard',
    galleryLayout: 'lightbox-focus',
    testimonialsLayout: 'minimal-inline',
    contactLayout: 'centered-form',
    footerLayout: 'minimal',
    animationPreset: 'fade-in',
    threeDEffects: { hero: 'none', cards: 'float', gallery: 'none', intensity: 25 },
    brandOverrides: { accentColor: '#c41e3a', backgroundColor: '#0a0a0a', textColor: '#e8e0d5', headingFont: 'Noto Serif JP', bodyFont: 'Noto Sans' },
    heroOverrides: { overlayOpacity: 0, alignment: 'center' },
    sectionStyles: { borderRadius: 'none', cardStyle: 'flat', sectionSpacing: 'spacious' },
  },
  {
    id: 'restaurant-bistro-parisien',
    name: 'Bistro Parisien',
    vertical: 'restaurant',
    designFamily: 'heritage',
    description: 'Chic Parisian atmosphere with cream and gold',
    previewGradient: 'linear-gradient(135deg, #f5f0e8 0%, #e8dcc8 50%, #8b6914 100%)',
    heroLayout: 'split',
    navStyle: 'centered',
    aboutLayout: 'full-width-image',
    galleryLayout: 'grid-uniform',
    testimonialsLayout: 'single-slider',
    contactLayout: 'card',
    footerLayout: 'centered',
    animationPreset: 'scale-up',
    threeDEffects: { hero: 'none', cards: 'tilt-cards', gallery: 'none', intensity: 40 },
    brandOverrides: { accentColor: '#8b6914', backgroundColor: '#faf6ee', textColor: '#2c2417', headingFont: 'Playfair Display', bodyFont: 'Crimson Text' },
    heroOverrides: { overlayOpacity: 30, alignment: 'center' },
    sectionStyles: { borderRadius: 'md', cardStyle: 'outlined', sectionSpacing: 'spacious' },
  },
  {
    id: 'restaurant-street-food',
    name: 'Street Food',
    vertical: 'restaurant',
    designFamily: 'brutalist',
    description: 'Bold and energetic with neon accents and urban vibes',
    previewGradient: 'linear-gradient(135deg, #1a1a1a 0%, #2d2d2d 50%, #ff6b35 100%)',
    heroLayout: 'bold-type',
    navStyle: 'solid',
    aboutLayout: 'cards-only',
    galleryLayout: 'carousel',
    testimonialsLayout: 'cards',
    contactLayout: 'split',
    footerLayout: 'standard',
    animationPreset: 'stagger-cascade',
    threeDEffects: { hero: 'float', cards: 'tilt-cards', gallery: 'perspective-grid', intensity: 70 },
    brandOverrides: { accentColor: '#ff6b35', backgroundColor: '#1a1a1a', textColor: '#ffffff', headingFont: 'Space Mono', bodyFont: 'Space Mono' },
    heroOverrides: { overlayOpacity: 65, alignment: 'center' },
    sectionStyles: { borderRadius: 'sm', cardStyle: 'elevated', sectionSpacing: 'compact' },
  },
  {
    id: 'restaurant-farm-table',
    name: 'Farm to Table',
    vertical: 'restaurant',
    designFamily: 'tropical',
    description: 'Organic warmth with natural greens and earthy palette',
    previewGradient: 'linear-gradient(135deg, #f4f0e6 0%, #d4c5a0 50%, #6b7f3b 100%)',
    heroLayout: 'stacked',
    navStyle: 'transparent',
    aboutLayout: 'zigzag',
    galleryLayout: 'masonry',
    testimonialsLayout: 'quote-wall',
    contactLayout: 'split',
    footerLayout: 'standard',
    animationPreset: 'fade-up',
    threeDEffects: { hero: 'none', cards: 'float', gallery: 'none', intensity: 30 },
    brandOverrides: { accentColor: '#6b7f3b', backgroundColor: '#faf7f0', textColor: '#2a2a1e', headingFont: 'DM Serif Display', bodyFont: 'DM Sans' },
    heroOverrides: { overlayOpacity: 20, alignment: 'center' },
    sectionStyles: { borderRadius: 'lg', cardStyle: 'flat', sectionSpacing: 'spacious' },
  },
  {
    id: 'restaurant-rooftop-lounge',
    name: 'Rooftop Lounge',
    vertical: 'restaurant',
    designFamily: 'noir',
    description: 'Sophisticated nightlife with deep purples and city glamour',
    previewGradient: 'linear-gradient(135deg, #0d0a1a 0%, #1a1030 50%, #9b59b6 100%)',
    heroLayout: 'parallax',
    navStyle: 'glass',
    aboutLayout: 'timeline',
    galleryLayout: 'filmstrip',
    testimonialsLayout: 'single-slider',
    contactLayout: 'card',
    footerLayout: 'mega',
    animationPreset: 'slide-in',
    threeDEffects: { hero: 'parallax-layers', cards: 'tilt-cards', gallery: 'perspective-grid', intensity: 60 },
    brandOverrides: { accentColor: '#9b59b6', backgroundColor: '#0d0a1a', textColor: '#f0e6ff', headingFont: 'Outfit', bodyFont: 'Sora' },
    heroOverrides: { overlayOpacity: 50, alignment: 'left' },
    sectionStyles: { borderRadius: 'lg', cardStyle: 'glass', sectionSpacing: 'normal' },
  },
  {
    id: 'restaurant-seafood-pier',
    name: 'Seafood Pier',
    vertical: 'restaurant',
    designFamily: 'coastal',
    description: 'Fresh coastal dining with ocean blues and nautical charm',
    previewGradient: 'linear-gradient(135deg, #0a1929 0%, #1565c0 50%, #e3f2fd 100%)',
    heroLayout: 'classic',
    navStyle: 'glass',
    aboutLayout: 'standard',
    galleryLayout: 'carousel',
    testimonialsLayout: 'cards',
    contactLayout: 'map-focus',
    footerLayout: 'standard',
    animationPreset: 'fade-up',
    threeDEffects: { hero: 'parallax-layers', cards: 'float', gallery: 'none', intensity: 40 },
    brandOverrides: { accentColor: '#1e88e5', backgroundColor: '#0a1929', textColor: '#e3f2fd', headingFont: 'Lora', bodyFont: 'Open Sans' },
    heroOverrides: { overlayOpacity: 45, alignment: 'left' },
    sectionStyles: { borderRadius: 'md', cardStyle: 'elevated', sectionSpacing: 'normal' },
  },
  {
    id: 'restaurant-tapas-bar',
    name: 'Tapas Bar',
    vertical: 'restaurant',
    designFamily: 'deco',
    description: 'Vibrant Spanish energy with warm reds and festive spirit',
    previewGradient: 'linear-gradient(135deg, #1a0a00 0%, #4a1a0a 50%, #e74c3c 100%)',
    heroLayout: 'diagonal',
    navStyle: 'solid',
    aboutLayout: 'cards-only',
    galleryLayout: 'grid-uniform',
    testimonialsLayout: 'cards',
    contactLayout: 'split',
    footerLayout: 'centered',
    animationPreset: 'stagger-cascade',
    threeDEffects: { hero: 'depth-scroll', cards: 'flip-reveal', gallery: 'none', intensity: 55 },
    brandOverrides: { accentColor: '#e74c3c', backgroundColor: '#1a0a00', textColor: '#ffeedd', headingFont: 'Poiret One', bodyFont: 'Raleway' },
    heroOverrides: { overlayOpacity: 55, alignment: 'center' },
    sectionStyles: { borderRadius: 'md', cardStyle: 'outlined', sectionSpacing: 'compact' },
  },
  {
    id: 'restaurant-fine-dining',
    name: 'Fine Dining',
    vertical: 'restaurant',
    designFamily: 'ethereal',
    description: 'Michelin-star elegance with dark moody ambiance',
    previewGradient: 'linear-gradient(135deg, #050505 0%, #1a1a1a 50%, #c9a84c 100%)',
    heroLayout: 'fullscreen-card',
    navStyle: 'transparent',
    aboutLayout: 'full-width-image',
    galleryLayout: 'lightbox-focus',
    testimonialsLayout: 'quote-wall',
    contactLayout: 'centered-form',
    footerLayout: 'minimal',
    animationPreset: 'fade-in',
    threeDEffects: { hero: 'depth-scroll', cards: 'float', gallery: 'none', intensity: 35 },
    brandOverrides: { accentColor: '#c9a84c', backgroundColor: '#050505', textColor: '#e8e0d0', headingFont: 'Cormorant Garamond', bodyFont: 'Jost' },
    heroOverrides: { overlayOpacity: 60, alignment: 'center' },
    sectionStyles: { borderRadius: 'sm', cardStyle: 'glass', sectionSpacing: 'spacious' },
  },
  {
    id: 'restaurant-cafe-modern',
    name: 'Cafe Modern',
    vertical: 'restaurant',
    designFamily: 'electric',
    description: 'Light and airy with soft pastels and playful design',
    previewGradient: 'linear-gradient(135deg, #fef9f3 0%, #fde8d0 50%, #e17055 100%)',
    heroLayout: 'split',
    navStyle: 'solid',
    aboutLayout: 'standard',
    galleryLayout: 'grid-uniform',
    testimonialsLayout: 'cards',
    contactLayout: 'card',
    footerLayout: 'centered',
    animationPreset: 'scale-up',
    threeDEffects: { hero: 'none', cards: 'tilt-cards', gallery: 'none', intensity: 35 },
    brandOverrides: { accentColor: '#e17055', backgroundColor: '#fef9f3', textColor: '#2d2016', headingFont: 'Clash Display', bodyFont: 'Sora' },
    heroOverrides: { overlayOpacity: 25, alignment: 'left' },
    sectionStyles: { borderRadius: 'full', cardStyle: 'elevated', sectionSpacing: 'normal' },
  },

  // ╔══════════════════════════════════════════════╗
  // ║  STORE TEMPLATES (10)                        ║
  // ╚══════════════════════════════════════════════╝

  {
    id: 'store-curated',
    name: 'Curated',
    vertical: 'store',
    designFamily: 'ethereal',
    description: 'Refined editorial feel with neutral tones and clean grid',
    previewGradient: 'linear-gradient(135deg, #faf9f7 0%, #e8e4de 50%, #8b5cf6 100%)',
    heroLayout: 'classic',
    navStyle: 'transparent',
    aboutLayout: 'standard',
    galleryLayout: 'masonry',
    testimonialsLayout: 'cards',
    contactLayout: 'split',
    footerLayout: 'standard',
    animationPreset: 'fade-up',
    threeDEffects: { hero: 'none', cards: 'tilt-cards', gallery: 'none', intensity: 40 },
    brandOverrides: { accentColor: '#8b5cf6', backgroundColor: '#faf9f7', textColor: '#111111', headingFont: 'Cormorant Garamond', bodyFont: 'Jost' },
    heroOverrides: { overlayOpacity: 50, alignment: 'left' },
    sectionStyles: { borderRadius: 'md', cardStyle: 'flat', sectionSpacing: 'normal' },
  },
  {
    id: 'store-streetwear',
    name: 'Streetwear',
    vertical: 'store',
    designFamily: 'brutalist',
    description: 'Bold urban aesthetic with high contrast and oversized type',
    previewGradient: 'linear-gradient(135deg, #000000 0%, #1a1a1a 50%, #ff3d00 100%)',
    heroLayout: 'bold-type',
    navStyle: 'solid',
    aboutLayout: 'cards-only',
    galleryLayout: 'carousel',
    testimonialsLayout: 'minimal-inline',
    contactLayout: 'split',
    footerLayout: 'standard',
    animationPreset: 'stagger-cascade',
    threeDEffects: { hero: 'depth-scroll', cards: 'tilt-cards', gallery: 'perspective-grid', intensity: 75 },
    brandOverrides: { accentColor: '#ff3d00', backgroundColor: '#000000', textColor: '#ffffff', headingFont: 'Space Mono', bodyFont: 'Space Mono' },
    heroOverrides: { overlayOpacity: 70, alignment: 'center' },
    sectionStyles: { borderRadius: 'none', cardStyle: 'outlined', sectionSpacing: 'compact' },
  },
  {
    id: 'store-artisan',
    name: 'Artisan',
    vertical: 'store',
    designFamily: 'wabi-sabi',
    description: 'Handcrafted warmth with organic shapes and earthy tones',
    previewGradient: 'linear-gradient(135deg, #f7f3ed 0%, #e4d5c1 50%, #b5651d 100%)',
    heroLayout: 'stacked',
    navStyle: 'transparent',
    aboutLayout: 'zigzag',
    galleryLayout: 'masonry',
    testimonialsLayout: 'quote-wall',
    contactLayout: 'card',
    footerLayout: 'centered',
    animationPreset: 'fade-up',
    threeDEffects: { hero: 'none', cards: 'float', gallery: 'none', intensity: 30 },
    brandOverrides: { accentColor: '#b5651d', backgroundColor: '#f7f3ed', textColor: '#2a1f14', headingFont: 'Noto Serif JP', bodyFont: 'Noto Sans' },
    heroOverrides: { overlayOpacity: 20, alignment: 'center' },
    sectionStyles: { borderRadius: 'lg', cardStyle: 'flat', sectionSpacing: 'spacious' },
  },
  {
    id: 'store-luxury-boutique',
    name: 'Luxury Boutique',
    vertical: 'store',
    designFamily: 'opulent',
    description: 'High-end fashion with black and gold minimalism',
    previewGradient: 'linear-gradient(135deg, #000000 0%, #1a1a1a 50%, #c9a84c 100%)',
    heroLayout: 'minimal',
    navStyle: 'minimal',
    aboutLayout: 'full-width-image',
    galleryLayout: 'lightbox-focus',
    testimonialsLayout: 'single-slider',
    contactLayout: 'centered-form',
    footerLayout: 'minimal',
    animationPreset: 'fade-in',
    threeDEffects: { hero: 'none', cards: 'float', gallery: 'none', intensity: 25 },
    brandOverrides: { accentColor: '#c9a84c', backgroundColor: '#000000', textColor: '#f5f0e8', headingFont: 'Bodoni Moda', bodyFont: 'Jost' },
    heroOverrides: { overlayOpacity: 0, alignment: 'center' },
    sectionStyles: { borderRadius: 'none', cardStyle: 'flat', sectionSpacing: 'spacious' },
  },
  {
    id: 'store-vintage-finds',
    name: 'Vintage Finds',
    vertical: 'store',
    designFamily: 'heritage',
    description: 'Retro nostalgia with warm sepia tones and classic serif type',
    previewGradient: 'linear-gradient(135deg, #f0e6d3 0%, #d4b896 50%, #8b4513 100%)',
    heroLayout: 'fullscreen-card',
    navStyle: 'centered',
    aboutLayout: 'timeline',
    galleryLayout: 'grid-uniform',
    testimonialsLayout: 'cards',
    contactLayout: 'split',
    footerLayout: 'mega',
    animationPreset: 'scale-up',
    threeDEffects: { hero: 'float', cards: 'flip-reveal', gallery: 'none', intensity: 45 },
    brandOverrides: { accentColor: '#8b4513', backgroundColor: '#f5efe3', textColor: '#2d1b0e', headingFont: 'Playfair Display', bodyFont: 'Crimson Text' },
    heroOverrides: { overlayOpacity: 35, alignment: 'center' },
    sectionStyles: { borderRadius: 'md', cardStyle: 'outlined', sectionSpacing: 'normal' },
  },
  {
    id: 'store-tech-minimal',
    name: 'Tech Minimal',
    vertical: 'store',
    designFamily: 'noir',
    description: 'Sleek product showcase with dark theme and blue accents',
    previewGradient: 'linear-gradient(135deg, #0a0a0f 0%, #111122 50%, #3b82f6 100%)',
    heroLayout: 'split',
    navStyle: 'glass',
    aboutLayout: 'cards-only',
    galleryLayout: 'carousel',
    testimonialsLayout: 'cards',
    contactLayout: 'centered-form',
    footerLayout: 'standard',
    animationPreset: 'slide-in',
    threeDEffects: { hero: 'depth-scroll', cards: 'tilt-cards', gallery: 'perspective-grid', intensity: 65 },
    brandOverrides: { accentColor: '#3b82f6', backgroundColor: '#0a0a0f', textColor: '#e0e7ff', headingFont: 'Outfit', bodyFont: 'Sora' },
    heroOverrides: { overlayOpacity: 40, alignment: 'left' },
    sectionStyles: { borderRadius: 'lg', cardStyle: 'glass', sectionSpacing: 'normal' },
  },
  {
    id: 'store-plant-shop',
    name: 'Plant Shop',
    vertical: 'store',
    designFamily: 'tropical',
    description: 'Fresh botanical aesthetic with lush greens and natural vibes',
    previewGradient: 'linear-gradient(135deg, #f0f7f0 0%, #c8e6c9 50%, #2e7d32 100%)',
    heroLayout: 'parallax',
    navStyle: 'transparent',
    aboutLayout: 'standard',
    galleryLayout: 'masonry',
    testimonialsLayout: 'cards',
    contactLayout: 'split',
    footerLayout: 'standard',
    animationPreset: 'fade-up',
    threeDEffects: { hero: 'parallax-layers', cards: 'float', gallery: 'none', intensity: 40 },
    brandOverrides: { accentColor: '#2e7d32', backgroundColor: '#f0f7f0', textColor: '#1b2e1b', headingFont: 'DM Serif Display', bodyFont: 'DM Sans' },
    heroOverrides: { overlayOpacity: 30, alignment: 'left' },
    sectionStyles: { borderRadius: 'lg', cardStyle: 'elevated', sectionSpacing: 'normal' },
  },
  {
    id: 'store-jewelry-atelier',
    name: 'Jewelry Atelier',
    vertical: 'store',
    designFamily: 'deco',
    description: 'Elegant rose gold with soft blush tones and refined detail',
    previewGradient: 'linear-gradient(135deg, #1a0f14 0%, #2d1a24 50%, #c77dba 100%)',
    heroLayout: 'diagonal',
    navStyle: 'centered',
    aboutLayout: 'zigzag',
    galleryLayout: 'lightbox-focus',
    testimonialsLayout: 'single-slider',
    contactLayout: 'card',
    footerLayout: 'centered',
    animationPreset: 'fade-in',
    threeDEffects: { hero: 'none', cards: 'tilt-cards', gallery: 'none', intensity: 35 },
    brandOverrides: { accentColor: '#c77dba', backgroundColor: '#1a0f14', textColor: '#f5e6f0', headingFont: 'Poiret One', bodyFont: 'Raleway' },
    heroOverrides: { overlayOpacity: 50, alignment: 'center' },
    sectionStyles: { borderRadius: 'full', cardStyle: 'glass', sectionSpacing: 'spacious' },
  },
  {
    id: 'store-bookstore',
    name: 'Bookstore',
    vertical: 'store',
    designFamily: 'coastal',
    description: 'Literary warmth with deep navy and amber accents',
    previewGradient: 'linear-gradient(135deg, #0d1421 0%, #1a2744 50%, #d4a373 100%)',
    heroLayout: 'classic',
    navStyle: 'solid',
    aboutLayout: 'standard',
    galleryLayout: 'grid-uniform',
    testimonialsLayout: 'quote-wall',
    contactLayout: 'split',
    footerLayout: 'mega',
    animationPreset: 'fade-up',
    threeDEffects: { hero: 'parallax-layers', cards: 'flip-reveal', gallery: 'none', intensity: 45 },
    brandOverrides: { accentColor: '#d4a373', backgroundColor: '#0d1421', textColor: '#e8dfd0', headingFont: 'Lora', bodyFont: 'Open Sans' },
    heroOverrides: { overlayOpacity: 55, alignment: 'left' },
    sectionStyles: { borderRadius: 'md', cardStyle: 'elevated', sectionSpacing: 'normal' },
  },
  {
    id: 'store-sneaker-vault',
    name: 'Sneaker Vault',
    vertical: 'store',
    designFamily: 'electric',
    description: 'Hyper-modern with electric gradients and dynamic energy',
    previewGradient: 'linear-gradient(135deg, #0a0a0a 0%, #1a0a2e 50%, #a855f7 100%)',
    heroLayout: 'mosaic',
    navStyle: 'glass',
    aboutLayout: 'cards-only',
    galleryLayout: 'filmstrip',
    testimonialsLayout: 'minimal-inline',
    contactLayout: 'split',
    footerLayout: 'standard',
    animationPreset: 'stagger-cascade',
    threeDEffects: { hero: 'depth-scroll', cards: 'tilt-cards', gallery: 'perspective-grid', intensity: 80 },
    brandOverrides: { accentColor: '#a855f7', backgroundColor: '#0a0a0a', textColor: '#f0e6ff', headingFont: 'Clash Display', bodyFont: 'Sora' },
    heroOverrides: { overlayOpacity: 60, alignment: 'center' },
    sectionStyles: { borderRadius: 'lg', cardStyle: 'glass', sectionSpacing: 'compact' },
  },

  // ╔══════════════════════════════════════════════╗
  // ║  TRAVEL TEMPLATES (10)                       ║
  // ╚══════════════════════════════════════════════╝

  {
    id: 'travel-explorer',
    name: 'Explorer',
    vertical: 'travel',
    designFamily: 'coastal',
    description: 'Adventure-forward with deep blue and dynamic motion',
    previewGradient: 'linear-gradient(135deg, #080d14 0%, #0f1a2e 50%, #4a9eff 100%)',
    heroLayout: 'classic',
    navStyle: 'glass',
    aboutLayout: 'standard',
    galleryLayout: 'masonry',
    testimonialsLayout: 'cards',
    contactLayout: 'split',
    footerLayout: 'standard',
    animationPreset: 'fade-up',
    threeDEffects: { hero: 'parallax-layers', cards: 'tilt-cards', gallery: 'none', intensity: 50 },
    brandOverrides: { accentColor: '#4a9eff', backgroundColor: '#080d14', textColor: '#ffffff', headingFont: 'Lora', bodyFont: 'Open Sans' },
    heroOverrides: { overlayOpacity: 50, alignment: 'left' },
    sectionStyles: { borderRadius: 'lg', cardStyle: 'glass', sectionSpacing: 'normal' },
  },
  {
    id: 'travel-backpacker',
    name: 'Backpacker',
    vertical: 'travel',
    designFamily: 'brutalist',
    description: 'Rugged and adventurous with earthy tones and bold type',
    previewGradient: 'linear-gradient(135deg, #1a1410 0%, #3d2b1f 50%, #e8a838 100%)',
    heroLayout: 'bold-type',
    navStyle: 'solid',
    aboutLayout: 'cards-only',
    galleryLayout: 'carousel',
    testimonialsLayout: 'cards',
    contactLayout: 'split',
    footerLayout: 'standard',
    animationPreset: 'stagger-cascade',
    threeDEffects: { hero: 'float', cards: 'tilt-cards', gallery: 'perspective-grid', intensity: 60 },
    brandOverrides: { accentColor: '#e8a838', backgroundColor: '#1a1410', textColor: '#f0e6d3', headingFont: 'Space Mono', bodyFont: 'Space Mono' },
    heroOverrides: { overlayOpacity: 55, alignment: 'center' },
    sectionStyles: { borderRadius: 'sm', cardStyle: 'elevated', sectionSpacing: 'compact' },
  },
  {
    id: 'travel-luxury-escape',
    name: 'Luxury Escape',
    vertical: 'travel',
    designFamily: 'opulent',
    description: 'Premium travel with elegant dark theme and gold touches',
    previewGradient: 'linear-gradient(135deg, #0a0a0a 0%, #1a1520 50%, #c9a84c 100%)',
    heroLayout: 'parallax',
    navStyle: 'transparent',
    aboutLayout: 'zigzag',
    galleryLayout: 'lightbox-focus',
    testimonialsLayout: 'single-slider',
    contactLayout: 'centered-form',
    footerLayout: 'minimal',
    animationPreset: 'fade-in',
    threeDEffects: { hero: 'parallax-layers', cards: 'float', gallery: 'none', intensity: 35 },
    brandOverrides: { accentColor: '#c9a84c', backgroundColor: '#0a0a0a', textColor: '#f5f0e8', headingFont: 'Bodoni Moda', bodyFont: 'Jost' },
    heroOverrides: { overlayOpacity: 45, alignment: 'center' },
    sectionStyles: { borderRadius: 'md', cardStyle: 'glass', sectionSpacing: 'spacious' },
  },
  {
    id: 'travel-island-hopper',
    name: 'Island Hopper',
    vertical: 'travel',
    designFamily: 'tropical',
    description: 'Tropical paradise with turquoise waters and sunset warmth',
    previewGradient: 'linear-gradient(135deg, #002b49 0%, #00687a 50%, #00c9a7 100%)',
    heroLayout: 'fullscreen-card',
    navStyle: 'glass',
    aboutLayout: 'standard',
    galleryLayout: 'carousel',
    testimonialsLayout: 'cards',
    contactLayout: 'card',
    footerLayout: 'standard',
    animationPreset: 'scale-up',
    threeDEffects: { hero: 'float', cards: 'tilt-cards', gallery: 'perspective-grid', intensity: 55 },
    brandOverrides: { accentColor: '#00c9a7', backgroundColor: '#002b49', textColor: '#e0f7fa', headingFont: 'DM Serif Display', bodyFont: 'DM Sans' },
    heroOverrides: { overlayOpacity: 40, alignment: 'center' },
    sectionStyles: { borderRadius: 'lg', cardStyle: 'glass', sectionSpacing: 'normal' },
  },
  {
    id: 'travel-city-break',
    name: 'City Break',
    vertical: 'travel',
    designFamily: 'noir',
    description: 'Metropolitan energy with sleek gradients and modern vibes',
    previewGradient: 'linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #e94560 100%)',
    heroLayout: 'split',
    navStyle: 'solid',
    aboutLayout: 'timeline',
    galleryLayout: 'grid-uniform',
    testimonialsLayout: 'minimal-inline',
    contactLayout: 'split',
    footerLayout: 'mega',
    animationPreset: 'slide-in',
    threeDEffects: { hero: 'depth-scroll', cards: 'tilt-cards', gallery: 'none', intensity: 50 },
    brandOverrides: { accentColor: '#e94560', backgroundColor: '#1a1a2e', textColor: '#edf2f4', headingFont: 'Outfit', bodyFont: 'Sora' },
    heroOverrides: { overlayOpacity: 35, alignment: 'left' },
    sectionStyles: { borderRadius: 'sm', cardStyle: 'outlined', sectionSpacing: 'normal' },
  },
  {
    id: 'travel-adventure-wild',
    name: 'Adventure Wild',
    vertical: 'travel',
    designFamily: 'wabi-sabi',
    description: 'Raw wilderness with deep greens and dramatic landscapes',
    previewGradient: 'linear-gradient(135deg, #0a1a0a 0%, #1a3a1a 50%, #4caf50 100%)',
    heroLayout: 'classic',
    navStyle: 'transparent',
    aboutLayout: 'full-width-image',
    galleryLayout: 'masonry',
    testimonialsLayout: 'quote-wall',
    contactLayout: 'split',
    footerLayout: 'standard',
    animationPreset: 'fade-up',
    threeDEffects: { hero: 'parallax-layers', cards: 'none', gallery: 'depth-scroll', intensity: 45 },
    brandOverrides: { accentColor: '#4caf50', backgroundColor: '#0a1a0a', textColor: '#e8f5e9', headingFont: 'Noto Serif JP', bodyFont: 'Noto Sans' },
    heroOverrides: { overlayOpacity: 50, alignment: 'left' },
    sectionStyles: { borderRadius: 'md', cardStyle: 'elevated', sectionSpacing: 'spacious' },
  },
  {
    id: 'travel-cruise-liner',
    name: 'Cruise Liner',
    vertical: 'travel',
    designFamily: 'deco',
    description: 'Elegant maritime theme with navy and white contrast',
    previewGradient: 'linear-gradient(135deg, #0a1628 0%, #1a3a5c 50%, #ffffff 100%)',
    heroLayout: 'diagonal',
    navStyle: 'centered',
    aboutLayout: 'zigzag',
    galleryLayout: 'filmstrip',
    testimonialsLayout: 'single-slider',
    contactLayout: 'card',
    footerLayout: 'centered',
    animationPreset: 'scale-up',
    threeDEffects: { hero: 'none', cards: 'flip-reveal', gallery: 'perspective-grid', intensity: 50 },
    brandOverrides: { accentColor: '#1565c0', backgroundColor: '#0a1628', textColor: '#e3f2fd', headingFont: 'Poiret One', bodyFont: 'Raleway' },
    heroOverrides: { overlayOpacity: 40, alignment: 'center' },
    sectionStyles: { borderRadius: 'lg', cardStyle: 'glass', sectionSpacing: 'normal' },
  },
  {
    id: 'travel-ski-resort',
    name: 'Ski Resort',
    vertical: 'travel',
    designFamily: 'ethereal',
    description: 'Alpine freshness with icy whites and cool blue accents',
    previewGradient: 'linear-gradient(135deg, #e8edf2 0%, #b0c4de 50%, #4682b4 100%)',
    heroLayout: 'stacked',
    navStyle: 'glass',
    aboutLayout: 'cards-only',
    galleryLayout: 'grid-uniform',
    testimonialsLayout: 'cards',
    contactLayout: 'centered-form',
    footerLayout: 'standard',
    animationPreset: 'fade-up',
    threeDEffects: { hero: 'none', cards: 'float', gallery: 'none', intensity: 30 },
    brandOverrides: { accentColor: '#4682b4', backgroundColor: '#f0f4f8', textColor: '#1a2a3a', headingFont: 'Cormorant Garamond', bodyFont: 'Jost' },
    heroOverrides: { overlayOpacity: 20, alignment: 'center' },
    sectionStyles: { borderRadius: 'md', cardStyle: 'flat', sectionSpacing: 'normal' },
  },
  {
    id: 'travel-safari-dream',
    name: 'Safari Dream',
    vertical: 'travel',
    designFamily: 'heritage',
    description: 'African savanna warmth with burnt orange and rich earth tones',
    previewGradient: 'linear-gradient(135deg, #1a0e05 0%, #3d2b1f 50%, #e88a2d 100%)',
    heroLayout: 'mosaic',
    navStyle: 'glass',
    aboutLayout: 'standard',
    galleryLayout: 'masonry',
    testimonialsLayout: 'cards',
    contactLayout: 'split',
    footerLayout: 'standard',
    animationPreset: 'stagger-cascade',
    threeDEffects: { hero: 'parallax-layers', cards: 'tilt-cards', gallery: 'none', intensity: 55 },
    brandOverrides: { accentColor: '#e88a2d', backgroundColor: '#1a0e05', textColor: '#f5e6d3', headingFont: 'Playfair Display', bodyFont: 'Crimson Text' },
    heroOverrides: { overlayOpacity: 45, alignment: 'left' },
    sectionStyles: { borderRadius: 'lg', cardStyle: 'elevated', sectionSpacing: 'normal' },
  },
  {
    id: 'travel-cultural-journey',
    name: 'Cultural Journey',
    vertical: 'travel',
    designFamily: 'electric',
    description: 'Rich cultural heritage with deep burgundy and artisanal feel',
    previewGradient: 'linear-gradient(135deg, #1a0a10 0%, #3a1428 50%, #a0522d 100%)',
    heroLayout: 'classic',
    navStyle: 'solid',
    aboutLayout: 'timeline',
    galleryLayout: 'masonry',
    testimonialsLayout: 'quote-wall',
    contactLayout: 'map-focus',
    footerLayout: 'mega',
    animationPreset: 'fade-up',
    threeDEffects: { hero: 'depth-scroll', cards: 'tilt-cards', gallery: 'depth-scroll', intensity: 50 },
    brandOverrides: { accentColor: '#a0522d', backgroundColor: '#1a0a10', textColor: '#f0e0d0', headingFont: 'Clash Display', bodyFont: 'Sora' },
    heroOverrides: { overlayOpacity: 55, alignment: 'left' },
    sectionStyles: { borderRadius: 'md', cardStyle: 'outlined', sectionSpacing: 'spacious' },
  },
];

export const templateRegistry = new Map(templates.map(t => [t.id, t]));

export function getTemplatesForVertical(vertical: string): TemplateDefinition[] {
  return templates.filter(t => t.vertical === vertical);
}

export function getTemplate(id: string): TemplateDefinition | undefined {
  return templateRegistry.get(id);
}

export const DEFAULT_TEMPLATE_IDS: Record<string, string> = {
  hotel: 'hotel-grand-luxury',
  restaurant: 'restaurant-trattoria',
  store: 'store-curated',
  travel: 'travel-explorer',
};
